uniqlo_user:
    resource: Uniqlo\UserBundle\Controller\WebController
    type:     annotation
    prefix:   /

user:
    type:     rest
    prefix:   /api
    resource: Uniqlo\UserBundle\Controller\UserController
